services:

  - type: web
    name: gymtracker-database
    env: docker
    plan: free
    image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root_password
      - key: MYSQL_DATABASE
        value: gymtracker
      - key: MYSQL_USER
        value: dad
      - key: MYSQL_PASSWORD
        value: padre
    ports:
      - 3306

  - type: web
    name: gymtracker-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    dockerContext: .
    envVars: []
    ports:
      - 8081

  - type: web
    name: gymtracker-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile.app
    dockerContext: .
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://gymtracker-database:3306/gymtracker
      - key: SPRING_DATASOURCE_USERNAME
        value: dad
      - key: SPRING_DATASOURCE_PASSWORD
        value: padre
      - key: SERVER_PORT
        value: 443
    ports:
      - 443
    dependsOn:
      - gymtracker-database
      - gymtracker-api